from django.urls import path

from . import admin_api, views

urlpatterns = [
    path("health/", views.health),
    path("auth/login/", views.login),
    path("auth/me/", views.me),
    path("auth/change-password/", views.change_password),
    path("auth/forgot-password/verify/", views.forgot_password_verify),
    path("auth/forgot-password/reset/", views.forgot_password_reset),
    path("auth/forgot-password/message-admin/", views.forgot_password_message_admin),
    path("auth/users/", views.users),
    path("auth/users/<str:user_id>/reset-password/", views.reset_password),
    path("auth/users/<str:user_id>/force-password-change/", views.force_password_change),
    path("dashboard/", views.dashboard),
    path("students/", views.students),
    path("students/bulk-import/", views.bulk_students),
    path("students/<str:student_id>/", views.student_detail),
    path("teachers/", views.teachers),
    path("teachers/<str:teacher_id>/", views.teacher_detail),
    path("attendance/", views.attendance),
    path("attendance/audit/", views.attendance_audit),
    path("attendance/<str:attendance_id>/lock/", lambda request, attendance_id: views.attendance_lock(request, attendance_id, True)),
    path("attendance/<str:attendance_id>/unlock/", lambda request, attendance_id: views.attendance_lock(request, attendance_id, False)),
    path("marks/", views.marks),
    path("notices/", views.notices),
    path("timetables/", views.timetables),
    path("fees/", views.fees),
    path("contact-messages/", views.contact_messages),
    path("videos/", views.videos),
    path("notes/<str:note_id>/bookmark/", views.note_bookmark),
    path("notes/", views.notes),
    path("blogs/", views.blogs),
    path("current-affairs/", views.current_affairs),
    path("assignments/", views.assignments),
    path("assignments/<str:assignment_id>/submit/", views.assignment_submit),
    path("question-bank/", admin_api.question_bank),
    path("question-bank/bulk-import/", admin_api.question_bank_bulk_import),
    path("practice/daily/", admin_api.daily_practice),
    path("practice/sessions/<str:session_id>/answers/", admin_api.practice_answer),
    path("practice/sessions/<str:session_id>/submit/", admin_api.practice_submit),
    path("practice/mistakes/", admin_api.practice_mistakes),
    path("practice/mistakes/<str:mistake_id>/practice-again/", admin_api.practice_again),
    path("practice/weak-topics/", admin_api.weak_topics),
    path("practice/study-plan/", admin_api.study_plan),
    path("practice/study-plan/tasks/<str:task_id>/complete/", admin_api.study_plan_task_complete),
    path("practice/analytics/", admin_api.practice_analytics),
    path("exams/", admin_api.exams),
    path("exams/<str:exam_id>/questions/", admin_api.exam_questions),
    path("exams/<str:exam_id>/start/", admin_api.exam_start),
    path("exams/<str:exam_id>/publish-results/", admin_api.exam_publish_results),
    path("exam-attempts/<str:attempt_id>/answers/", admin_api.exam_attempt_answer),
    path("exam-attempts/<str:attempt_id>/submit/", admin_api.exam_attempt_submit),
    path("exam-attempts/<str:attempt_id>/violation/", admin_api.exam_attempt_violation),
    path("exam-attempts/<str:attempt_id>/evaluate/", admin_api.exam_attempt_evaluate),
    path("notifications/", views.notifications),
    path("notifications/mark-all-read/", views.notifications_mark_all_read),
    path("notifications/<str:notification_id>/read/", views.notification_mark_read),
    path("notifications/<str:notification_id>/", views.notification_dismiss),
    path("ai/chat/", views.ai_chat),
]